import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import Navigation from "@/components/layout/Sidebar";



export const metadata: Metadata = {
  title: "Mailer kayhan audio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation />
       <div className="pl-[5rem]" >
         {children}
       </div>
      </body>
    </html>
  );
}
