import type { Metadata } from "next";
import Navigation from "@/components/layout/Sidebar";
import AuthProvider from "@/components/gloabl/AuthProvider"; 

export const metadata: Metadata = {
  title: "Mailer kayhan audio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <AuthProvider>
          <div className="pl-[5rem]">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
